# import turtle as t
# import random
# def timmy():
#     tim = t.Turtle
#
#     tim.circle(120, 180)  # draw a semicircle
#     tim.position()
#     # tim.color(random.randint(0 , 255))
# timmy()
#
#
# from turtle import *
# screen = Screen()
# screen.setup(width=1000, height=600)
# penup()
# speed(10)
# goto(-500 , 400)
# for step in range(15):
#     write(step,  align="center")
#     right(90)
#     forward(50)
#     pendown()
#     forward(1500)
#     penup()
#     backward(1600)
#     left(90)
#     forward(50)
# screen.exitonclick()
#!/bin/python3
from turtle import *
from random import randint
# write(0)
# forward(20)
# write(1)
# forward(20)
# write(2)
# forward(20)
# write(3)
# forward(20)
# write(4)
# forward(20)
# write(5)
penup()
goto(-140 , 140)
speed(10)
for step in range(15):
  write(step, align="center")
  right(90)
  forward(10)
  pendown()
  forward(150)
  penup()
  backward(160)
  left(90)
  forward(20)
tim = Turtle()
tim.color("red")
tim.shape("turtle")
tim.penup()
tim.goto(-160 , 100)
tim.pendown()
timmy = Turtle()
timmy.color("blue")
timmy.shape("turtle")
timmy.penup()
timmy.goto(-160 , 80)
timmy.pendown()
tom = Turtle()
tom.color("orange")
tom.shape("turtle")
tom.penup()
tom.goto(-160 , 60)
tom.pendown()
tonny = Turtle()
tonny.color("purple")
tonny.shape("turtle")
tonny.penup()
tonny.goto(-160 , 40)
tonny.pendown()
for turn in range(100):
  tim.forward(randint(1,5))
  timmy.forward(randint(1,5))
  tom.forward(randint(1,5))
  tonny.forward(randint(1,5))